# Generated by Django 4.2.5 on 2023-10-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
