# Generated by Django 4.2.5 on 2023-10-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_place_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='PinCode',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
