# Generated by Django 4.2.5 on 2023-10-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_place_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='district',
            field=models.IntegerField(default=None),
        ),
    ]
