# Generated by Django 4.2.5 on 2023-10-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_place_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='PinCode',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='priority',
            field=models.IntegerField(default=None),
        ),
    ]
