# Generated by Django 4.2.5 on 2023-10-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_place_pincode_alter_place_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='priority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
