# Generated by Django 4.2.5 on 2023-10-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_place_pincode_alter_place_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='fgxffdg',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
